### ISSUE TITLE
Exception loading model

### ISSUE THREAD

**Issue by DatrixTHLK** [TeamBR-Modding/Bookshelf#13]
Hello @Dyonovan ,

I seem to be getting this error mentioned in the FML Log: 
https://gist.github.com/DatrixTHLK/732365a23e0815aff4bcad49bf280955

Lines 1869-1962

**Comment by Dyonovan** [comment]
That can be ignored.

**Comment by DatrixTHLK** [comment]
This is definitely spammed a lot in the FML Log though. Is there no way to lessen it? If it is to be ignored I will do so,
