### ISSUE TITLE
sometimes the world does´t load in 1.10.2

### ISSUE THREAD

**Issue by Realever** [TeamBR-Modding/Bookshelf#14]
hi 
when i load my world i see on the screen 0% is loadet and nothing happens.When show in the log there is was written from "There was a critical exception handling a packet on channel BOOKSHELFAPI".But when i start minecraft new then load my world.here is the log:  http://paste.ee/p/UbK4O . I hope you can me help.Sorry my english is not so good.

**Comment by pauljoda** [comment]
Link is dead, if still having a problem reopen
