### ISSUE TITLE
Crash during start up

### ISSUE THREAD

**Issue by athenashavoc** [TeamBR-Modding/Bookshelf#15]
When using both ver 5.0.0-B92 and 5.0.0-B86. I've tried deleting config for both Bookshell and Assisted Progression and still experience the crash. 

Reverting to ver 4.0.0 works

https://paste.ee/p/9HoQC

**Comment by pauljoda** [comment]
Do not use the latest Bookshelf. We have updated our core mod and not Assisted Progression
