### ISSUE TITLE
Crash with alpha version of Bookshelf with Tiny Progressions

### ISSUE THREAD

**Issue by Medusalem** [TeamBR-Modding/Bookshelf#16]
Forge version: 13.20.0.2299
Mincraft 1.11.2 

Bookshelf version 381 and 380 (thats what i tested)
Tiny Progressions all 1.11.2 versions

crashlog: https://pastebin.com/efU1b3nn

Kashdeya send me over, said he suspects it to be on your end, if not you should message him :)

**Comment by pauljoda** [comment]
This is the wrong bookshelf. You want the one by darkax we are the bookshelf api
