### ISSUE TITLE
two Bookshelf APIs - double naming

### ISSUE THREAD

**Issue by walkerjonny** [TeamBR-Modding/Bookshelf#2]
Hi, 
there is another API around there that is also called Bookshelf API.
http://minecraft.curseforge.com/projects/bookshelf
Could you please talk together to find a solution for that double naming issue.

**Comment by Darkhax** [comment]
Hello @pauljoda and @Dyonovan. I am not sure what way is best to contact either of you, so I have moved the discussion over here. Please let me know if you are interested in working with us to resolve this issue. And if so, where you wish to discuss this.

**Comment by pauljoda** [comment]
I'd be totally fine with discussing things. As for a medium, I am fine with whatever. Let me know what works best for you

**Comment by Darkhax** [comment]
Do you use IRC? We have the #Bookshelf channel on esper.net.

**Comment by walkerjonny** [comment]
Are there any news on that?

**Comment by Darkhax** [comment]
The two teams have been talking, however we have not reached a solution.

**Comment by walkerjonny** [comment]
Thank you for the status update. Take the time you need.

**Comment by Dyonovan** [comment]
I am working on changing the mod ID as we speak. Will take a day or 2 as I am also doing some work on NeoTech

**Comment by Dyonovan** [comment]
Ok. Changed an published. We are using bookshelfapi now.

**Comment by walkerjonny** [comment]
Thank you all for finding a solution for it!

**Comment by SvEgiiVEteR** [comment]
when to wait for 1710?

**Comment by SvEgiiVEteR** [comment]
http://i.imgur.com/PTvHa2N.png
