### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by nikkimas** [TeamBR-Modding/Bookshelf#3]
Hi, when I start my game with Bookshelfapi it crashes(does not look like the potion error).
The thing is, it only crashes on my Laptop, yes I tried different java versions :).

Here the Crash:
http://pastebin.com/iDXjGEyG

P.S.: Sorry if it's not bookshelfapi causing it. I'm very bad at crash-report reading!

**Comment by Dyonovan** [comment]
Your using a very old version of Java 8. I recommend you update. 

As its not working on the laptop, but it is on your other computer, this issue seems to be your java on the laptop

**Comment by nikkimas** [comment]
.okay, it still crashes. I use 1.8.0_73. But it looks like minecraft was using the "onboard" java before(the version that comes with the mc launcher)

http://pastebin.com/01U6ySY1

**Comment by Dyonovan** [comment]
It looks like you are missing some libraries from forge. Forge installs the scala library. Try reinstalling forge

**Comment by nikkimas** [comment]
It started! Thank you soo much! I really need to learn how to read crash-reports :/. 

Thanks!

**Comment by Dyonovan** [comment]
No problem.
