### ISSUE TITLE
Server Crash on Load

### ISSUE THREAD

**Issue by Darkosto** [TeamBR-Modding/Bookshelf#6]
MC Version: 1.9
Forge Version: 1796
Mod Version: Bookshelf-API-1.9-3.0.0

Are you aware of this crash on load with Bookshelf?

http://pastebin.com/fCFDhiLE

**Comment by pauljoda** [comment]
Yes, forge updated and moved classes. We are working on getting a release out but we are working with issues with MultiPart. Might not be ready for a little bit
