### ISSUE TITLE
JEI Compat Crash

### ISSUE THREAD

**Issue by CandiceJoy** [TeamBR-Modding/Bookshelf#7]
https://goo.gl/q25gSa

In my pack, For the Love of Adventure Part Deux (1.8.9) if you pull up the recipe for the watering can in JEI and click the button to the right a few times, it will crash with this error.

**Comment by Dyonovan** [comment]
Umm, thats a picture, not a crash log :)

**Comment by CandiceJoy** [comment]
Derp, sorry!  https://cdn.discordapp.com/attachments/178637405803249665/178637614272872450/crash-2016-05-08_00.40.29-client.txt
